#!/bin/bash
claro
[[ "$(whoami)" != "raíz" ]] && {
echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33mvocê precisa ejecutar como root\033[0m"
rm $HOME/Plus > /dev/null 2>&1; salida 0
}
_lnk=$(echo 't1:e#n.5s0ul&p4hs$s.0729t9p$&8i&&9r7827c032:3s'| sed -e 's/[^az.]//ig'| rev); _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^az/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^az/]//ig')
cd $HOME
diversión_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $INICIO/fim ]] && rm $INICIO/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
toque $HOME/fim
 ) > /desarrollo/null 2>&1 &
 tput civil
echo -ne " \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
mientras que cierto; hacer
   para((i=0; i<18; i++)); hacer
   echo -ne "\033[1;31m#"
   dormir 0.1s
   hecho
   [[ -e $INICIO/fim ]] && rm $INICIO/fim && romper
   eco -e "\033[1;33m]"
   dormir 1s
   poner cuu1
   poner dl1
   echo -ne " \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
hecho
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
función clave_verif () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Tinta/lista > /dev/null 2>&1
[[ ! -e "$_Tinta/lista" ]] && {
  echo -e "\n\033[1;31mLISTA DE ARCHIVOS INVÁLIDA!\033[0m"
  rm -rf $HOME/Plus > /dev/null 2>&1
  dormir 2
  claro; salida 1
}
}
echo -e "\033[1;31m══════════════════════════════════════════ ════════════\033[0m"
tputsetaf7; poner setab 4 ; poner en negrita; printf '%40s%s%-12s\n' "BEM VINDO AO SSHPLUS MANAGER" ; poner sgr0
echo -e "\033[1;31m══════════════════════════════════════════ ════════════\033[0m"
eco ""
echo -e " \033[1;31mATENCAO! \033[1;33mESSE SCRIPT IRA !\033[0m"
eco ""
echo -e "\033[1;31m• \033[1;33mINSTALAR UM CONJUNTO DE SCRIPTS COMO FERRAMENTAS\033[0m"
echo -e "\033[1;33m PARA O GERENCIAMENTO DE REDE, SISTEMA E USUARIOS\033[0m"
eco ""
echo -e "\033[1;32m• \033[1;32mDICA! \033[1;33mULTILIZE O TEMA DARK EM SEU TERMINAL PARA\033[0m"
echo -e "\033[1;33m UMA MEJOR EXPERIÊNCIA E VISUALIZACAO DO MESMO!\033[0m"
eco ""
echo -e "\033[1;31m≠×≠×≠×≠×≠×≠×≠×≠×[\033[1;33m • \033[1;32mBY CRAZY VPN\033[1;33m •\ 033[1;31m ]≠×≠×≠×≠×≠×≠×≠×≠×\033[0m"
eco ""
read -p "$(echo -e "\033[1;36mDESEJA CONTINUAR \033[1;31m? \033[1;33m[S/N]:\033[1;37m")" -e -is resp
[[ $resp = @(n|N) ]] && rm $HOME/Plus && exit 0
_lnk2=$(echo "$clave"|awk -F : '{imprimir $2}'); _lnk1=$(echo "$clave"|awk -F : '{imprimir $1}')
echo -e "\n\033[1;36mVERIFICANDO...\033[1;37m Lista de archivos\033[0m" ; rm $_Ink/lista > /dev/null 2>&1; wget -P $_Ink https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/SSHPLUS-MANAGER-FREE/master/Install/list > /dev/null 2>&1; clave_verif
echo -e "\n\033[1;32mLISTA DE ARCHIVOS VÁLIDA!\033[1;32m"
dormir 1s
eco ""
[[ -f "$HOME/usuarios.db" ]] && {
    claro
    echo -e "\n\033[0;34m════════════════════════════════════════ ═══════════\033[0m"
    eco ""
	echo -e " \033[1;33m• \033[1;31mATENCAO \033[1;33m• \033[0m"
	eco ""
    echo -e "\033[1;33mUma base de Dados de Usuarios \033[1;32m(usuarios.db) \033[1;33mFoi"
    echo -e "Encontrada! Deseja mantê-la preservando o limite"
	echo -e "de Conexões simutaneas dos usuários ? Ou Deseja"
    echo -e "criar uma nova base de datos ?\033[0m"
	echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mManter Base de Dados Atual\033[0m"
	echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCriar uma Nova Base de Dados\033[0m"
	echo -e "\n\033[0;34m════════════════════════════════════════ ═══════════\033[0m"
    eco ""
	tputsetaf 2 ; poner en negrita; read -p "Opção?: " -e -i 1 optiondb ; poner sgr0
} || {
	awk -F : '$3 >= 500 { imprimir $1 " 1" }' /etc/passwd | grep -v '^nadie' > $HOME/usuarios.db
}
[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nadie' > $HOME/usuarios.db
claro
tputsetaf7; poner setab 4 ; poner en negrita; printf '%35s%s%-18s\n' " AGUARDE A INSTALAÇÃO" ; poner sgr0
eco ""
eco ""
echo -e " \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mATUALIZANDO SISTEMA \033[1;33m[\033[1;31m!\033[1 ;33m]\033[0m"
eco ""
echo -e " \033[1;33mATUALIZAÇÕES COSTUMA DEMORAR UM POUCO!\033[0m"
eco ""
diversión_attlist () {
    apt-obtener actualización -y
	[[ ! -d /usr/compartir/.plus ]] && mkdir /usr/compartir/.plus
	echo "crz: $(fecha)" > /usr/share/.plus/.plus
}
fun_bar 'fun_attlist'
claro
eco ""
echo -e " \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mINSTALANDO PACOTES \033[1;33m[\033[1;31m!\033[1 ;33m] \033[0m"
eco ""
echo -e "\033[1;33mALGUNS PACOTES SAO EXTREMAMENTE NECESARIOS !\033[0m"
eco ""
pct_inst () {
_pacotes=("bc" "pantalla" "nano" "descomprimir" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip")
para _prog en ${_pacotes[@]}; hacer
    instalación apt $_prog -y
hecho
pip install speedtest-cli
}
fun_bar 'inst_pct'
[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw permite 80/tcp; ufw permite 3128/tcp; ufw permite 8799/tcp; ufw permite 8080/tcp
claro
eco ""
echo -e " \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mFINALIZANDO \033[1;33m[\033[1;31m!\033[1; 33m] \033[0m"
eco ""
echo -e " \033[1;33mCONCLUINDO FUNCIONES Y DEFINICIONES! \033[0m"
eco ""
fun_bar "$_Ink/lista $_lnk $_Ink $_1nk $clave"
rm -rf $INICIO/verificación del sistema* > /dev/null 2>&1; bash <(wget -qO- https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/SSHPLUS-MANAGER-FREE/master/Install/systemverify)
claro
eco ""
cd $HOME
echo -e " \033[1;33m • \033[1;32mINSTALACAO CONCLUIDA\033[1;33m • \033[0m"
eco ""
echo -e "\033[1;31m \033[1;33mCOMANDO PRINCIPAL: \033[1;32mmenú\033[0m"
echo -e "\033[1;33m MAIS INFORMACOES \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37m@AAAAAEXQOSyIpN2JZ0ehUQ\033[0m"
rm $HOME/Plus && cat /dev/null > ~/.bash_history && historial -c
